---
title: "Organizing Committee"
---

## Conference Leadership

### Conference Chairs

**[Jason Hawkins](mailto:jason.hawkins@ucalgary.ca)** - University of Calgary, Canada

**[Giancarlos Parady](mailto:parady@bin.t.u-tokyo.ac.jp)** - The University of Tokyo, Japan

### Program Chairs

**[Mehrnaz Ghamami](mailto:ghamami@msu.edu)** - Michigan State University, USA

**[Yong-Hong Kuo](mailto:yhkuo@hku.hk)** - University of Hong Kong, China

**[Jahedul Alam](mailto:jahedul@dal.ca)** - Dalhousie University, Canada

### Specialized Roles

**Headliner Coordinator:**
[Jinping (Jenna) Guan](mailto:jenna.guan@hit.edu.cn) - Harbin Institute of Technology, Shenzhen, China & MIT, USA

**Paper Review Coordinator:**
[Mahmoud Mesbah](mailto:m.mesbah@aut.ac.ir) - Tehran Polytechnic, Iran

### Technical Leadership

**Technical Leads:**

[Mehmet Yildirimoglu](mailto:m.yildirimoglu@uq.edu.au) - University of Queensland, Australia

[Jun Liu](mailto:jliu@eng.ua.edu) - University of Alabama, USA

### Communications & Outreach

**Publicity Chairs:**

[Kara Kockelman](mailto:kkockelm@mail.utexas.edu) - University of Texas at Austin, USA

[Elnaz Irannezhad](mailto:elnaz.irannezhad@unsw.edu.au) - University of New South Wales (UNSW), Australia

[Yong-Hong Kuo](mailto:yhkuo@hku.hk) - University of Hong Kong, China

**Special Issues Chairs:**

[Elnaz Irannezhad](mailto:elnaz.irannezhad@unsw.edu.au) - University of New South Wales (UNSW), Australia

[Mahmoud Mesbah](mailto:m.mesbah@aut.ac.ir) - Tehran Polytechnic, Iran

[Jahedul Alam](mailto:jahedul@dal.ca) - Dalhousie University, Canada

### Additional Committee Members

**Organizing Committee:**
[Samuel Labi](mailto:labi@purdue.edu) - Purdue University

**Webmaster:**
[Hiroshi Uemura](mailto:uemura@bin.t.u-tokyo.ac.jp) - The University of Tokyo, Japan

## Want to Join Us?

**We would like to sincerely thank our volunteers and reviewers.** Without their dedication and effort, it is impossible to manage this online conference with removing the barriers (e.g. visa barriers + travel hassles) and zero cost of travel and greenhouse gas emissions.

*Please keep spreading the word* in your research community and international conferences. And *encourage your colleagues in other disciplines to enable carbon-free cost-free conferencing* for other research communities. We're happy to provide guidance!

### Volunteer Opportunities

If you're interested in volunteering for BTR, we welcome contributions from the transportation research community. Volunteer roles include:

- **Session moderators**
- **Technical support**
- **Paper review**
- **Social media promotion**
- **Website maintenance**
- **Registration assistance**

To volunteer, please contact us at [bridgingtransport@gmail.com](mailto:bridgingtransport@gmail.com) with your area of interest and availability.

## Contact the Committee

For specific inquiries related to different aspects of the conference:

- **General questions:** [bridgingtransport@gmail.com](mailto:bridgingtransport@gmail.com)
- **Paper submissions:** Contact Program Chairs
- **Technical issues:** Contact Technical Leads
- **Media inquiries:** Contact Publicity Chairs
- **Sponsorship opportunities:** Contact Conference Chairs
